/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yeepay.bigdata.crawler.schedule.thrift;


import org.apache.thrift.TEnum;

/**
 * 服务响应状态值
 */
public enum ResponseStatus implements TEnum {
  Success(0),
  Failure(1);

  private final int value;

  private ResponseStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ResponseStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return Success;
      case 1:
        return Failure;
      default:
        return null;
    }
  }
}
