/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yeepay.bigdata.crawler.crawl.thrift.service;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 抓取任务结果状态
 */
public enum CrawlerTaskResultStatus implements TEnum {
  Succeed(0),
  Failure(1),
  Error(2);

  private final int value;

  private CrawlerTaskResultStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CrawlerTaskResultStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return Succeed;
      case 1:
        return Failure;
      case 2:
        return Error;
      default:
        return null;
    }
  }
}
