/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yeepay.bigdata.crawler.heartbeat.thrift.service;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * worker 类型： 目前包括：
 */
public enum WorkerType implements TEnum {
  CRAWLER(0),
  EXTRACTOR(1);

  private final int value;

  private WorkerType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static WorkerType findByValue(int value) { 
    switch (value) {
      case 0:
        return CRAWLER;
      case 1:
        return EXTRACTOR;
      default:
        return null;
    }
  }
}
