/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.yeepay.bigdata.crawler.extractor.thrift.service;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * 提取结果类型
 */
public enum ExtractResultType implements TEnum {
  PAGE(0),
  LIST(1),
  RSSLIST(2);

  private final int value;

  private ExtractResultType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ExtractResultType findByValue(int value) { 
    switch (value) {
      case 0:
        return PAGE;
      case 1:
        return LIST;
      case 2:
        return RSSLIST;
      default:
        return null;
    }
  }
}
